on:
  schedule:
  - cron:  "*/30 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://git.eclipse.org/r/tracecompass.incubator/org.eclipse.tracecompass.incubator.git"
        source_branch: "*"
        destination_branch: "*"
        sync_tags: "true"
        github_token: ${{ secrets.PAT }}
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge master back to repo-sync-do-not-delete
      run: |
          git fetch --unshallow
          git checkout repo-sync-do-not-delete
          git pull
          git merge --no-ff master -m "Auto-merge master back to repo-sync-do-not-delete"
          git push
